### YamlMime:BusinessCentralApplicationObject
fqName: '"EOMDB Customer Applications"'
alId: ID 70656862
baseKind: Query
kind: Query
parent: 'N:Module::Bankfeed_-_Core::Namespace::'
langs:
- al
seeAlso:
- '[Query](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-query-object)'
objectProperties:
- name: Caption
  value: Customer Applications
  promoted: false
- name: QueryType
  value: Normal
  promoted: false
- name: DataAccessIntent
  value: ReadOnly
  promoted: false
- name: ReadState
  value: ReadUncommitted
  promoted: false
- name: OrderBy
  value: descending(entryNumber)
  promoted: false
queryColumns:
- dataItem: Cust__Ledger_Entry
  columnType:
    name: None
    isExternal: true
  name: entryNumber
  uid: C:Query::EOMDB_Customer_Applications.Cust__Ledger_Entry.entryNumber
- dataItem: Cust__Ledger_Entry
  columnType:
    name: None
    isExternal: true
  name: customerNumber
  uid: C:Query::EOMDB_Customer_Applications.Cust__Ledger_Entry.customerNumber
- dataItem: Cust__Ledger_Entry
  columnType:
    name: None
    isExternal: true
  name: postingDate
  uid: C:Query::EOMDB_Customer_Applications.Cust__Ledger_Entry.postingDate
- dataItem: Cust__Ledger_Entry
  columnType:
    name: None
    isExternal: true
  name: documentType
  uid: C:Query::EOMDB_Customer_Applications.Cust__Ledger_Entry.documentType
- dataItem: Cust__Ledger_Entry
  columnType:
    name: None
    isExternal: true
  name: documentNumber
  uid: C:Query::EOMDB_Customer_Applications.Cust__Ledger_Entry.documentNumber
- dataItem: Cust__Ledger_Entry
  columnType:
    name: None
    isExternal: true
  name: remainingAmount
  uid: C:Query::EOMDB_Customer_Applications.Cust__Ledger_Entry.remainingAmount
- dataItem: Detailed_Cust__Ledg__Entry
  columnType:
    name: None
    isExternal: true
  name: applicationAmount
  uid: C:Query::EOMDB_Customer_Applications.Cust__Ledger_Entry.Detailed_Cust__Ledg__Entry.applicationAmount
- dataItem: Detailed_Cust__Ledg__Entry
  columnType:
    name: None
    isExternal: true
  name: applicationCreatedDateTime
  uid: C:Query::EOMDB_Customer_Applications.Cust__Ledger_Entry.Detailed_Cust__Ledg__Entry.applicationCreatedDateTime
commentId: O:Query::EOMDB Customer Applications
name: '"EOMDB Customer Applications"'
uid: O:Query::EOMDB_Customer_Applications
